[package]
name = "vdflex"
version = "0.1.1"
authors = ["Evan Hedbor <evan@hedbor.org>"]
edition = "2021"

[dependencies]
indexmap = { version = "2.0", optional = true }
indoc = "2.0"
serde = { version ="1.0", optional = true }
thiserror = "1.0"

[features]
default = ["std"]
preserve_order = ["indexmap"]
std = ["serde?/std", "indexmap?/std"]
